# Generated by Django 4.2.2 on 2024-04-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(upload_to='cheat_sheets/')),
            ],
        ),
    ]
