from django.shortcuts import render

#aarya edit
from django.http import HttpResponse

# Create your views here.

def home(request):
    return HttpResponse("HomePage")
def contact(request):
    return render(request,'MYAPP/dashboard.html')
def contact2(request):
    return render(request,'MYAPP/resources.html')
def index(request):
    context = {
        'pageTitle': 'Data Science',
        'paragraph1': 'This is the first paragraph of the content.',
        'paragraph2': 'Data Science is a multidisciplinary field that combines techniques from mathematics, statistics, computer science, and domain-specific knowledge to extract insights and knowledge from structured and unstructured data. It encompasses a wide range of methodologies, including data collection, data cleaning, data preprocessing, exploratory data analysis, statistical modeling, machine learning, and data visualization. Data scientists use various tools and programming languages such as Python, R, SQL, and specialized libraries and frameworks like pandas, scikit-learn, TensorFlow, and PyTorch to analyze and interpret data. The field of Data Science has become increasingly important in recent years due to the exponential growth of data generated by businesses, social media, IoT devices, and other sources. Companies across industries leverage data science techniques to make data-driven decisions, improve products and services, optimize operations, enhance customer experience, and gain competitive advantages in the market. Data Science also plays a crucial role in addressing societal challenges, including healthcare, environmental sustainability, finance, education, and public policy. As the demand for skilled data scientists continues to rise, Data Science has emerged as one of the most sought-after and lucrative career paths, offering opportunities for professionals with expertise in data analysis, machine learning, artificial intelligence, and related domains. Data Science is a rapidly evolving field that leverages advanced techniques and methodologies to extract actionable insights and knowledge from large and complex datasets. It encompasses a wide range of disciplines, including statistics, mathematics, computer science, and domain expertise, to solve real-world problems and drive informed decision-making. Data scientists employ various tools and technologies such as programming languages like Python and R, statistical modeling techniques, machine learning algorithms, and data visualization libraries to analyze and interpret data. They work with diverse datasets, including structured data from databases and spreadsheets, as well as unstructured data from text documents, images, videos, and social media streams. Data Science finds applications in a variety of domains, including business analytics, finance, healthcare, marketing, cybersecurity, and social sciences. Organizations use data science to gain insights into customer behavior, predict market trends, detect fraud and anomalies, optimize processes, and improve products and services. With the advent of big data and the proliferation of data sources, the demand for skilled data scientists continues to grow, making Data Science an exciting and rewarding field for professionals seeking to make a meaningful impact in todays data-driven world.',
        'btnLink': '#',
        'btnText': 'Click Here'
    }
    return render(request, 'MYAPP/index.html', context)




#PDF FORM
# views.py
from django.http import HttpResponse
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from django.shortcuts import render
from .admin import MyForm

# def generate_pdf(request):
#     if request.method == 'POST':
#         form = MyForm(request.POST)
#         if form.is_valid():
#             # Extract form data
#             name = form.cleaned_data['name']
#             age = form.cleaned_data['age']
            
#             # Generate PDF
#             response = HttpResponse(content_type='application/pdf')
#             response['Content-Disposition'] = 'attachment; filename="output.pdf"'
#             p = canvas.Canvas(response, pagesize=letter)
#             p.drawString(100, 750, "Name: " + name)
#             p.drawString(100, 730, "Age: " + str(age))
#             p.save()
#             return response
#     else:
#         form = MyForm()
#     return render(request, 'MYAPP/resources.html', {'form': form})

from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
import io

# def generate_pdf(request):
#     # Render the HTML template
#     template = get_template('MYAPP/index.html')
#     context = {}  # Add any context data here
#     html = template.render(context)

#     # Create a PDF response
#     response = HttpResponse(content_type='application/pdf')
#     response['Content-Disposition'] = 'attachment; filename="output.pdf"'

#     # Generate PDF from HTML
#     pisa_status = pisa.CreatePDF(html, dest=response)
#     if pisa_status.err:
#         return HttpResponse('PDF generation error!')

#     return response
def generate_pdf(request):
    # Render the HTML template
    template = get_template('MYAPP/index.html')
    context = {
        'pageTitle': 'Data Science',
        'paragraph1': 'This is the first paragraph of the content.',
        'paragraph2': 'Data Science is a multidisciplinary field that combines techniques from mathematics, statistics, computer science, and domain-specific knowledge to extract insights and knowledge from structured and unstructured data. It encompasses a wide range of methodologies, including data collection, data cleaning, data preprocessing, exploratory data analysis, statistical modeling, machine learning, and data visualization. Data scientists use various tools and programming languages such as Python, R, SQL, and specialized libraries and frameworks like pandas, scikit-learn, TensorFlow, and PyTorch to analyze and interpret data. The field of Data Science has become increasingly important in recent years due to the exponential growth of data generated by businesses, social media, IoT devices, and other sources. Companies across industries leverage data science techniques to make data-driven decisions, improve products and services, optimize operations, enhance customer experience, and gain competitive advantages in the market. Data Science also plays a crucial role in addressing societal challenges, including healthcare, environmental sustainability, finance, education, and public policy. As the demand for skilled data scientists continues to rise, Data Science has emerged as one of the most sought-after and lucrative career paths, offering opportunities for professionals with expertise in data analysis, machine learning, artificial intelligence, and related domains. Data Science is a rapidly evolving field that leverages advanced techniques and methodologies to extract actionable insights and knowledge from large and complex datasets. It encompasses a wide range of disciplines, including statistics, mathematics, computer science, and domain expertise, to solve real-world problems and drive informed decision-making. Data scientists employ various tools and technologies such as programming languages like Python and R, statistical modeling techniques, machine learning algorithms, and data visualization libraries to analyze and interpret data. They work with diverse datasets, including structured data from databases and spreadsheets, as well as unstructured data from text documents, images, videos, and social media streams. Data Science finds applications in a variety of domains, including business analytics, finance, healthcare, marketing, cybersecurity, and social sciences. Organizations use data science to gain insights into customer behavior, predict market trends, detect fraud and anomalies, optimize processes, and improve products and services. With the advent of big data and the proliferation of data sources, the demand for skilled data scientists continues to grow, making Data Science an exciting and rewarding field for professionals seeking to make a meaningful impact in todays data-driven world.',
        'btnLink': '#',
        'btnText': 'Click Here'
    }
    html = template.render(context)

    # Create a PDF file
    result = io.BytesIO()
    pdf = pisa.pisaDocument(io.BytesIO(html.encode("UTF-8")), result)

    # Return PDF as response
    if not pdf.err:
        response = HttpResponse(result.getvalue(), content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="my_website.pdf"'
        return response
    return HttpResponse('Error rendering PDF', status=500)


